debugger:
  # host: blog.dev # default: localhost
  port: 9005 # default: 9005
  # lineOffset: 10 # default: 6
  # path: ./public/ # default: null
  # file: index.php # default: null
  # verboseMode: false # default: false
  # historyFile: ~/.dephpugger_history # default: .dephpugger_history
server:
  # host: localhost # default: localhost
  port: 8000 # default: 8888
  path: ./public/
